version: '2'

services:
  web:
    build: ./
    restart: always
    ports: 
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      - GITHUB_USER
      - GITHUB_PASSWORD
      - ZENHUB_API_TOKEN
      - SECRET_KEY
      - MONGO_HOST
      - DEFAULT_REPO_ID
      - DEFAULT_REPO_NAME
      - SLACK_TOKEN
      - ADMIN_USER
      - ADMIN_PASSWD
    depends_on:
      - db

  db:
    build: ./db/
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
